### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by matthiasn** [DeLaGuardo/setup-clojure#1]
This is working fine for both Mac and Linux, that's great! However, with Windows it says that that isn't supported yet. Do you have plans to implement that soon? Thanks

**Comment by DeLaGuardo** [comment]
Yes, it is planned. At least leiningen and boot will be supported in next release.

**Comment by tangjeff0** [comment]
Hi, what all would need to be done to support Windows? Thanks!

**Comment by DeLaGuardo** [comment]
Hi, please check out `windows-support` branch. Just added setup for leiningen into it.

Example:

```
- uses: DeLaGuardo/setup-clojure@windows-support
  with:
    lein: latest
```

**Comment by DeLaGuardo** [comment]
you can track progress here - https://github.com/DeLaGuardo/setup-clojure/pull/9
