### ISSUE TITLE
Latency regression in latest releases

### ISSUE THREAD

**Issue by dhleong** [DeLaGuardo/setup-clojure#108]
Hello! I've been using v3 in CI for quite some time, but when I went to set up a new project I thought I'd dust off the cobwebs and clean up some warnings that github was showing about old versions. I have not tried to bisect or anything, but version 12.5 took 2 minutes to run (!), and most of it appeared to be just hanging after the "post" step of writing to cache. I downgraded to 3.5 (which includes version updates, at least) and it was back to running almost instantaneously. Is this something you're seeing elsewhere as well, or is it something peculiar about my setup?

Thanks for your help and all your work on these actions!

**Comment by frenchy64** [comment]
I'm also seeing this.

Here's a build that pauses for 2m even after a cache hit: https://github.com/threatgrid/ctia/actions/runs/11637562591/job/32410961520?pr=1453#step:6:20

Possibly related, here's another build that saves a cache that seems to have already been a cache hit: https://github.com/threatgrid/ctia/actions/runs/11598161623/job/32293388110#step:6:24

**Comment by frenchy64** [comment]
FWIW the symptoms remind me of https://github.com/actions/cache/issues/597

It might also be worth bumping the actions/cache dependency.

**Comment by frenchy64** [comment]
@dhleong Could you try `DeLaGuardo/setup-clojure@ba4fbfd343c802d2533385b040b59d2e290e18f7`?

**Comment by DeLaGuardo** [comment]
@dhleong Please try the new 12.6 release and let me know if you still expirience this issue. Huge shout out to @frenchy64 for the fix.

**Comment by dhleong** [comment]
That seems to have fixed it for me! Thank you both 🙏
