### ISSUE TITLE
build now failing due to github blocking set-env

### ISSUE THREAD

**Issue by dharrigan** [DeLaGuardo/setup-clojure#16]
Hi,

From today, November 16 2020, github has blocked all `set-env` commands from working, i.e.,

```
The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

This is now causing the action to fail to build projects:

```
Unable to process command '::set-env name=CLOJURE_INSTALL_DIR,::/opt/hostedtoolcache/ClojureToolsDeps/1.10.1-708/x64/lib/clojure' successfully.
```

and

```
The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

and

```
Run DeLaGuardo/setup-clojure@2.0
/bin/tar xz -C /home/runner/work/_temp/temp_898646021 -f /home/runner/work/_temp/c1015bd7-c452-4207-b9fd-c514fc8975d0
Error: Unable to process command '::set-env name=CLOJURE_INSTALL_DIR,::/opt/hostedtoolcache/ClojureToolsDeps/1.10.1-708/x64/lib/clojure' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::add-path::/opt/hostedtoolcache/ClojureToolsDeps/1.10.1-708/x64/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Is there a remediation for this?

**Comment by filipesilva** [comment]
Meanwhile you can set the env variable as described in the error message:
```
      - uses: DeLaGuardo/setup-clojure@2.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          tools-deps: '1.10.1.536'
```

**Comment by dharrigan** [comment]
Hi,

Thank you - happy to use that in the interim until a new release is out :-) Thank you!

**Comment by DeLaGuardo** [comment]
Hi, this issue has already being fixed in master. Please use `DeLaGuardo/setup-clojure@master` this string in your actions to get latest code.

**Comment by dharrigan** [comment]
Hi,

No problem, will do! Thank you. Is master encouraged now rather than tagged releases?

**Comment by DeLaGuardo** [comment]
yes, it is encouraged for free hot-fixes (like the one connected with using `set-env`). You could also use sha-based versioning (`DeLaGuardo/setup-clojure@e73bf2b6435244b2c9c5c226ae5022d91d0ce702`) pattern if you don't like floating release pointers.

**Comment by dharrigan** [comment]
Hi,

Not a problem - happy to use master. I was asking since it's been a while since the 2.0 release (over 1 year) and since that release no longer works with the changes github has made, but master does, would it be time to do a new release now, like a 2.1 or 3.0? :-)

**Comment by DeLaGuardo** [comment]
https://github.com/DeLaGuardo/setup-clojure/issues/15#issuecomment-726636612
here is my thoughts about tagged releases vs. branch/sha )
Also I'm writing a blog post about this situation

**Comment by dharrigan** [comment]
Thank you for the explanation. I'll close this ticket now as by switching to @master, the problem has been fixed.
