### ISSUE TITLE
Use of deprecated commands?

### ISSUE THREAD

**Issue by pmonks** [DeLaGuardo/setup-clojure#17]
[My build](https://github.com/pmonks/futbot/blob/main/.github/workflows/build.yml) (which has been working for ~6 months) just stopped working, with this error:
```
The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
In looking at the [linked blog post](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/), it appears that some changes are necessary in the workflow action to ensure it continues to function correctly.

**Comment by DeLaGuardo** [comment]
Hi, this was already fixed in master branch. Please use `DeLaGuardo/setup-clojure@master`
