### ISSUE TITLE
set-env and add-path commands are disabled

### ISSUE THREAD

**Issue by liquidz** [DeLaGuardo/setup-clojure#18]
Currently `set-env` and `add-path` commands are disabled on GitHub Actions.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

```
Error: Unable to process command '::set-env name=CLOJURE_INSTALL_DIR,::/opt/hostedtoolcache/ClojureToolsDeps/1.10.1-536/x64/lib/clojure' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::add-path::/opt/hostedtoolcache/ClojureToolsDeps/1.10.1-536/x64/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by DeLaGuardo** [comment]
This was already resolved. Please use `DeLaGuardo/setup-clojure@master` in your workflow

**Comment by liquidz** [comment]
@DeLaGuardo Oh sorry! I used `@2.0`.
I confirmed `@master` works well. Thanks!

BTW do you have a plan to cut a new tag?
I'd like to use a fixed version instead of `@master`, if possible.

**Comment by DeLaGuardo** [comment]
I gave my ideas why I don't want to use tagged releases here — https://github.com/DeLaGuardo/setup-clojure/issues/15#issuecomment-726636612
If you want "stable" (not floating) release you could use sha-based release: `DeLaGuardo/setup-clojure@e73bf2b6435244b2c9c5c226ae5022d91d0ce702`

**Comment by liquidz** [comment]
Sorry for the duplicate issue. I should have checked.
I'll use sha-based release.

**Comment by DeLaGuardo** [comment]
Don't be sorry) That is ok, I'm happy to help)
