### ISSUE TITLE
Windows support for clojure cli

### ISSUE THREAD

**Issue by ericdallo** [DeLaGuardo/setup-clojure#20]
Maybe we can add support for clojure cli for windows: https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows

**Comment by ericdallo** [comment]
I'm not sure how to skip the user input for the location though

**Comment by DeLaGuardo** [comment]
Yeah, I'm also unsure what to do with user input. I don't have enough experience with windows stack yet. But I keep coming back to that issue once a month to check the progress with different installers.

**Comment by ericdallo** [comment]
I just copied the `iw` line to my CI and it worked perfectly on windows :)
I think is just add that line

**Comment by DeLaGuardo** [comment]
this one?
`iwr -useb download.clojure.org/install/win-install-1.10.3.814.ps1 | iex`

**Comment by ericdallo** [comment]
Yep :)
https://github.com/clojure-lsp/clojure-lsp/blob/master/.github/workflows/release.yml#L213-L220

**Comment by DeLaGuardo** [comment]
perfect! I will update setup-clojure right away. Thanks for the update!

**Comment by ericdallo** [comment]
Great! odd, I didn't need to configure anything for user input, good to know

**Comment by DeLaGuardo** [comment]
Just published new version (3.2) with windows support. 
There are some caveats described in release notes: https://github.com/DeLaGuardo/setup-clojure/releases/tag/3.2

**Comment by ericdallo** [comment]
Looks awesome, thank you for the quick improvement, this action rocks!
