### ISSUE TITLE
tests never completing

### ISSUE THREAD

**Issue by awb99** [DeLaGuardo/setup-clojure#25]
I use an interactive test runner. This never completes with setup-clojure in github actions.

```
:test-clj {:extra-paths ["test"]
             :extra-deps  {eftest/eftest {:mvn/version "0.5.7"}}
             :main-opts   ["-e"  "(require,'[eftest.runner,:refer,[find-tests,run-tests]]),(run-tests,(find-tests,\"test\"))"]}
```

**Comment by DeLaGuardo** [comment]
Hi, could you confirm that your tests complete somewhere else (locally for example)

**Comment by awb99** [comment]
Yes. Locally tests complete. I think it is the interactive terminal yo that
does not work in the ci.
