### ISSUE TITLE
Clojure isn't install in Windows when `cli: latest`

### ISSUE THREAD

**Issue by eggplants** [DeLaGuardo/setup-clojure#36]
In Windows, clojure installs in not `latest` but `1.10.3.1040`.

Failed (`cli: latest`):
https://github.com/eggplants/clj-xmas/actions/runs/1597572281
Passed (`latest`->`"1.10.3.1040"`):
https://github.com/eggplants/clj-xmas/actions/runs/1597588106

**Comment by eggplants** [comment]
❌: `https://download.clojure.org/install/win-install-latest.ps1`
⭕: `https://download.clojure.org/install/win-install-1.10.3.1040.ps1`

**Comment by DeLaGuardo** [comment]
thanks! please check 3.7 version. 'latest' version for cli on windows should be fixed now
