### ISSUE TITLE
Consider supporting deps.exe on Windows

### ISSUE THREAD

**Issue by lread** [DeLaGuardo/setup-clojure#47]
I don't know if this is radical or what.

But... [the deps.clj binary can be a nice replacement](https://github.com/borkdude/deps.clj#binary) for `clojure` on Windows.
It works on all Windows shells (not just powershell).

If you like the idea, I'd recommend the installer rename `deps.exe` to `clojure.exe` for a seamless CI replacement.

**Comment by lread** [comment]
In case you are curious, [here's what I do to install deps.exe for rewrite-clj](https://github.com/clj-commons/rewrite-clj/blob/45e4c914fb49fc0a6d939a58cf21ff5de9bc2ea4/.github/workflows/unit-test.yml#L81-L87).

**Comment by zharinov** [comment]
Not related directly, but @DeLaGuardo would you like to have support for more binaries hosted with github releases, like `babashka` does? Right now I've made action for [zprint](https://github.com/zharinov/setup-zprint/) formatter, though someone may prefer to have `cljstyle` or `cljfmt`.

I remember your argument about Unix way of separating things that do their thing good, but to the another hand, even Unix CLI tools have some meta-level curation mechanisms like "distribution" and "package manager".

**Comment by cap10morgan** [comment]
This is the only way I've found to get Clojure CLI & GraalVM's native-image to play nicely together on Windows. The official Clojure CLI installation requires Powershell, but GraalVM native-image has to be run from a special cmd.exe w/ certain env vars set by an MS dev tools batch file (Windows man... 🙄). Would be awesome if this action could install it!
