### ISSUE TITLE
latest for cli should only use latest stable version

### ISSUE THREAD

**Issue by puredanger** [DeLaGuardo/setup-clojure#75]
I just had an issue where someone using `cli: latest` got the new _alpha_ version that I released last night and are seeing issues due to changes in the alpha. The CLI has both dev and stable versions, and imo the `cli: latest` should only give you latest stable as we often have interim unstable releases. 

I see in the code you're basing this on the Windows powershell installer version. That's probably on the path to deprecation and removal so this current strategy is likely to be broken eventually anyways. There are a couple of places you can look to find the latest stable version. One is here: https://github.com/clojure/homebrew-tools/blob/master/Formula/clojure.rb 

And I have just created a new place here:
https://download.clojure.org/install/stable.properties

**Comment by DeLaGuardo** [comment]
Thanks for the link. Very helpful! `stable.properties` looks fantastic. I'll adjust the action to fetch it if the "latest" version is requested.

About PowerShell installer — as far as I know, this is the only "official" way to install Clojure CLI on windows. Are you evaluating some alternatives at the moment?

**Comment by puredanger** [comment]
> About PowerShell installer — as far as I know, this is the only "official" way to install Clojure CLI on windows. Are you evaluating some alternatives at the moment?

Yes, there is a discussion going about using an [MSI installer](https://github.com/casselc/clj-msi) and [deps.clj](https://github.com/borkdude/deps.clj). Where those would be hosted and built is still TBD.

**Comment by puredanger** [comment]
Thanks!
