### ISSUE TITLE
Babashka Support

### ISSUE THREAD

**Issue by daaku** [DeLaGuardo/setup-clojure#8]
Would you be open to adding babashka as another tool? Babashka provides a handy way to write the build scripts in clojure, for my use case anyway.

**Comment by DeLaGuardo** [comment]
Yes, why not) Could you make a PR?

Also there is already an action available in GitHub Marketplace that allows to run babashka scripts https://github.com/marketplace/actions/babashka-clojure

**Comment by daaku** [comment]
Great, I'll take a stab. The one you linked to is a docker action, I prefer having it installed like the other tools.
