### ISSUE TITLE
Update to node 16+

### ISSUE THREAD

**Issue by nickpell** [DeLaGuardo/setup-clojure#81]
I've been seeing this warning in GitHub Actions annotations:

```Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: DeLaGuardo/setup-clojure@8.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.```

**Comment by DeLaGuardo** [comment]
thanks for the heads up. I'll fix it asap

**Comment by DeLaGuardo** [comment]
This was fixed a while ago. Please upgrade to the latest 10.1 version of this action, and the warning will disappear.

**Comment by nickpell** [comment]
@DeLaGuardo Got it, thanks!
