### ISSUE TITLE
Builds failing due to HTTP 404

### ISSUE THREAD

**Issue by tatut** [DeLaGuardo/setup-clojure#93]
![image](https://github.com/DeLaGuardo/setup-clojure/assets/83725/f20e1e57-dbae-403a-9073-e34e7f14c6be)

Using latest master (12.0) fails to install Clojure CLI due to 404.

Downgrading to `setup-clojure@11.0` works.

**Comment by DeLaGuardo** [comment]
Please update to 12.1. This should fix this issue.

**Comment by DeLaGuardo** [comment]
@tatut 404 happened because of https://github.com/DeLaGuardo/setup-clojure/issues/88#issuecomment-1708617415
